version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3307"
    environment:
      - MYSQL_DATABASE=crops
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ../config/redis.conf:/usr/local/etc/redis/redis.conf # Redis conf 파일 지정
    command: redis-server /usr/local/etc/redis/redis.conf # 실행할 Command 명령어
    user: root  # root 권한으로 실행
    restart: always # Redis 컨테이너가 종료되면 자동으로 재시작

volumes:
  mysql_data:
  redis_data: